source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/minsol/MinsolSpec.git'   # 私有库

target 'demo' do

  # Pods for demo
#    pod 'TestLib'
#    pod 'YDTAppPrivate'
#    pod 'YDTAdvertising', :path => "/Users/minsol/Desktop/MinsolPrivate/YDTAdvertising"
#    pod 'YDTAdvertising'
    pod 'A8HttpMessage'

end

